[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/cart/c/*"
  to = "https://nichijo.myshopify.com/cart/c/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/checkout/*"
  to = "https://nichijo.myshopify.com/checkout/:splat"
  status = 200
  force = true
